### ISSUE TITLE
Error with environment.yml

### ISSUE THREAD

**Issue by GaspardQin** [araffin/robotics-rl-srl#33]
**Describe the bug**
Conda cannot analyse this file correctly, test on two computers with the same output. Do not why for now.

**How to solve**
I solved it by delete "Anaconda" from channels
And it should add "mujoco-py==1.50.1.56", the newer mujoco-py version need a mujoco installed with licence.

**Code example**
conda env update -f environment.yml

**System Info**

 ERROR REPORT 

    Traceback (most recent call last):
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 216, in _load
        mod_etag_headers.get('_mod'))
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 553, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_update.py", line 126, in execute
        installer.install(prefix, specs, args, env)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 35, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 438, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 179, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 560, in _prepare
        self.subdirs, prepared_specs)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 94, in query
        self.load()
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 148, in load
        _internal_state = self._load()
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 222, in _load
        mod_etag_headers.get('_mod'))
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 269, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/chuan/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 348, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /home/chuan/anaconda3/bin/conda-env update -f environment.yml`

**Comment by araffin** [comment]
Related to https://github.com/hill-a/stable-baselines/issues/65
Will be fixed with the new stable-baselines version

**Comment by araffin** [comment]
Fixed on master
