### ISSUE TITLE
TypeError: learn() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by HankerSia** [araffin/robotics-rl-srl#58]
for some network reasons, i download this code, and installed related package. When testing, I got a error.

**Describe the bug**
Traceback (most recent call last):
  File "/home/kai/anaconda3/envs/tf_torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kai/anaconda3/envs/tf_torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kai/robotics-rl-srl/rl_baselines/train.py", line 337, in <module>
    main()
  File "/home/kai/robotics-rl-srl/rl_baselines/train.py", line 333, in main
    algo.train(args, callback, env_kwargs=env_kwargs, train_kwargs=hyperparams)
  File "/home/kai/robotics-rl-srl/rl_baselines/rl_algorithm/ppo2.py", line 73, in train
    super().train(args, callback, env_kwargs, {**param_kwargs, **train_kwargs})
  File "/home/kai/robotics-rl-srl/rl_baselines/base_classes.py", line 252, in train
    self.model.learn(total_timesteps=args.num_timesteps, seed=args.seed, callback=callback)
TypeError: learn() got an unexpected keyword argument 'seed'

can anyone give me some advice. thank you!

**Comment by araffin** [comment]
Hello,

This is due to a newer version of Stable-Baselines.
The seed argument was moved to the model class constructor.
As I'm no longer maintaining this repo, I would appreciate a PR that solves this issue ;)
